---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.table(unz("activity.zip", "activity.csv"), header=T, quote="\"", sep=",")
str(data)


## What is mean total number of steps taken per day?
steps.date <- aggregate(steps~date,activity,sum)
hist(steps.date$steps, xlab="Total steps by day", ylab="Frequency [Days]",main="Histogram : Number of daily steps")

## Mean and Median
mean1 <- mean(steps.date$steps, na.rm=TRUE)
median1 <- median(steps.date$steps, na.rm=TRUE)

## What is the average daily activity pattern?
steps.interval <- aggregate(steps ~ interval, data=activity, FUN=mean)
plot(steps.interval, type="l",xlab="interval [in 5min]", ylab="Average daily activity pattern of steps",  main="average number of steps")

## Which 5-minute interval
steps.interval$interval[which.max(steps.interval$steps)]

## Imputing missing values

activity.merged = merge(activity, steps.interval, by="interval")
activity.merged$steps.x[is.na(activity.merged$steps.x)] = activity.merged$steps.y[is.na(activity.merged$steps.x)]

## Make a histogram of the total number of steps taken each day

activity.merged <- aggregate(steps.x~interval,activity.merged,sum)
hist(activity.merged$steps.x, xlab="Total steps by day", ylab="Frequency [Days]",main="Histogram : Number of daily steps")

## Mean and Median
mean2 <- mean(activity.merged$steps, na.rm=TRUE)
median2 <- median(activity.merged$steps, na.rm=TRUE)

## Are there differences in activity patterns between weekdays and weekends?
daytype <- function(date) {
    if (weekdays(as.Date(date)) %in% c("Saturday", "Sunday")) {
        "weekend"
    } else {
        "weekday"
    }
}
activity$daytype <- as.factor(sapply(activity$date, daytype))
str(activity)
## plot
par(mfrow=c(2,1))
for (type in c("weekend", "weekday")) {
    steps.type <- aggregate(steps ~ interval,
                            data=activity,
                            subset=activity$daytype==type,
                            FUN=mean)
    plot(steps.type, type="l", main=type)
}
